"""empty message

Revision ID: 0647a96e8968
Revises: 
Create Date: 2021-09-25 23:32:31.097632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0647a96e8968'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id_author', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_author')
    )
    op.create_index(op.f('ix_author_author_name'), 'author', ['author_name'], unique=True)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('passw', sa.String(), nullable=True),
    sa.Column('adm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_adm'), 'users', ['adm'], unique=True)
    op.create_index(op.f('ix_users_passw'), 'users', ['passw'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('book',
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id_author'], ),
    sa.PrimaryKeyConstraint('id_book')
    )
    op.create_index(op.f('ix_book_book_name'), 'book', ['book_name'], unique=True)
    op.create_index(op.f('ix_book_year'), 'book', ['year'], unique=True)
    op.create_table('orders',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id_book'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_index(op.f('ix_orders_price'), 'orders', ['price'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_price'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_book_year'), table_name='book')
    op.drop_index(op.f('ix_book_book_name'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_passw'), table_name='users')
    op.drop_index(op.f('ix_users_adm'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_author_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
