"""empty message

Revision ID: 25b1828de2d2
Revises: 0647a96e8968
Create Date: 2021-09-29 21:19:41.580279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b1828de2d2'
down_revision = '0647a96e8968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.String(), nullable=True))
    op.drop_index('ix_users_passw', table_name='users')
    op.create_index(op.f('ix_users_pass_hash'), 'users', ['pass_hash'], unique=True)
    op.drop_column('users', 'passw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passw', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_pass_hash'), table_name='users')
    op.create_index('ix_users_passw', 'users', ['passw'], unique=False)
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###
