"""empty message

Revision ID: 474d99a889eb
Revises: 6c8ef124c4bf
Create Date: 2021-10-15 21:44:18.196216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474d99a889eb'
down_revision = '6c8ef124c4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('ACTIVE', 'OPENED', 'CLOSED', name='status'), nullable=True))
    op.drop_column('orders', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
