"""empty message

Revision ID: 6c8ef124c4bf
Revises: 
Create Date: 2021-10-15 21:40:14.016150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8ef124c4bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('Active', 'Opened', 'Closed', name='status'), nullable=True))
    op.drop_column('orders', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
