"""empty message

Revision ID: fa147f5bcc04
Revises: 
Create Date: 2021-10-04 07:45:31.174341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa147f5bcc04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_year', table_name='book')
    op.drop_index('ix_orders_is_active', table_name='orders')
    op.drop_index('ix_orders_price', table_name='orders')
    op.drop_index('ix_users_adm', table_name='users')
    op.drop_index('ix_users_pass_hash', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_pass_hash', 'users', ['pass_hash'], unique=False)
    op.create_index('ix_users_adm', 'users', ['adm'], unique=False)
    op.create_index('ix_orders_price', 'orders', ['price'], unique=False)
    op.create_index('ix_orders_is_active', 'orders', ['is_active'], unique=False)
    op.create_index('ix_book_year', 'book', ['year'], unique=False)
    # ### end Alembic commands ###
